### ISSUE TITLE
Doen't work in Ubuntu 19.04

### ISSUE THREAD

**Issue by PJSingh5000** [linux-man/gnome-shell-extension-printers#11]
I've installed Ubuntu 19.04 on a few machines, and I've installed this extension on each.

The extension no longer lists my HP printer, on all the machines I've installed it on.

(The printers do appear in the gnome settings app.)

**Comment by linux-man** [comment]
Did you change interface to system-config-printer?
When using Gnome Control Center the extension don't list printers - there is no direct way to access printers spool.

**Comment by PJSingh5000** [comment]
Thanks for the quick response!

Yes, I had changed the interface to "Gnome Control Center" instead of system-config-printer.
I changed it to ""system-config-printer, and now I see the list of printers in this extension's Gnome tob bar menu.

(I seem to remember seeing the list of printers while still having "Gnome Control Center" selected, but I must be mistaken).
