### ISSUE TITLE
Get error in debian 10 stable

### ISSUE THREAD

**Issue by natxooy** [linux-man/gnome-shell-extension-printers#12]
Debian 10 stable. Installed cups and openprinting-ppd, ... and getting error. Any other package to be installed?, something else?

Thanks

**Comment by linux-man** [comment]
One essential package is "cups-bsd" which is not a dependency of cups, just a suggested package.

**Comment by natxooy** [comment]
Thanks!!! "apt install cups-bsd" adn it's working.

**Comment by linux-man** [comment]
You're welcome!

**Comment by fawtytoo** [comment]
I had an error after installing your extension. Installing the package cups-bsd fixed it.

You should put that into your extension description and the README.

**Comment by linux-man** [comment]
Done on both. I really should make a package, but it's not the gnomish way...
