### ISSUE TITLE
Problem after suspend - two logins neccessary

### ISSUE THREAD

**Issue by speedy-10** [linux-man/gnome-shell-extension-printers#17]
If this extension is installed, I need sometimes two longin-trys. 

My system:
5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Gnome 3.36.4 Distro: Ubuntu 20.04.1 LTS (Focal Fossa) 

Therefore I add my observation of `journalctl -r` after login:
`gnome-shell[23404]: Usage of object.actor is deprecated for PrintersManager
                                                   get@resource:///org/gnome/shell/ui/environment.js:287:29
                                                   refresh/</</</<@/home/$USER/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:180:147
                                                   spawn_async@/home/$USER/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:36:5
                                                   refresh/</</<@/home/$USER/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:143:21
                                                   spawn_async@/home/$USER/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:36:5
                                                   refresh/</<@/home/$USER/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:133:17
                                                   spawn_async@/home/$USER/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:36:5
                                                   refresh/<@/home/$USER/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:113:13
                                                   spawn_async@/home/$USER/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:36:5
                                                   refresh@/home/$USER/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:111:9
                                                   wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
                                                   onCupsSignal@/home/$USER/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:198:14
                                                   wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
                                                   _init@/home/$USER/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:74:10
                                                   wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
                                                   enable@/home/$USER/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:214:23
                                                   _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
                                                   _enableAllExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:612:22
                                                   _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:611:37
                                                   _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:639:18
                                                   _emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
                                                   _sync@resource:///org/gnome/shell/ui/sessionMode.js:198:14
                                                   popMode@resource:///org/gnome/shell/ui/sessionMode.js:166:14
                                                   _continueDeactivate@resource:///org/gnome/shell/ui/screenShield.js:502:30
                                                   deactivate/<@resource:///org/gnome/shell/ui/screenShield.js:493:44
                                                   finish@resource:///org/gnome/shell/gdm/authPrompt.js:523:13
                                                   finish@resource:///org/gnome/shell/ui/unlockDialog.js:867:26
                                                   deactivate@resource:///org/gnome/shell/ui/screenShield.js:493:26
                                                   ScreenShield/</<@resource:///org/gnome/shell/ui/screenShield.js:110:57
                                                   _emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
                                                   _convertToNativeSignal@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:169:19
`
It would be nice if you could possibly sove that.
Regards Speedy-10

**Comment by linux-man** [comment]
I'm not sure if "Usage of object.actor is deprecated" is the culprit, but that was not corrected thanks to inertia™ and laziness™.
Can you please replace extension.js at ~/.local/share/gnome-shell/extensions/printers@linux-man.org?
I'm sure that most of that error messages will vanish. Let's see what's left.
[extension.js.zip](https://github.com/linux-man/gnome-shell-extension-printers/files/5198110/extension.js.zip)

**Comment by speedy-10** [comment]
hi, changed file, here the latest output from journalctl -r:

`Sep 10 14:00:24 $USER-buero gnome-shell[23404]: Usage of object.actor is deprecated for PrintersManager
                                                   get@resource:///org/gnome/shell/ui/environment.js:287:29
                                                   refresh/</</</<@/home/$USER/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:180:147
                                                   spawn_async@/home/$USER/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:36:5
                                                   refresh/</</<@/home/$USER/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:143:21
                                                   spawn_async@/home/$USER/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:36:5
                                                   refresh/</<@/home/$USER/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:133:17
                                                   spawn_async@/home/$USER/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:36:5
                                                   refresh/<@/home/$USER/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:113:13
                                                   spawn_async@/home/$USER/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:36:5
                                                   refresh@/home/$USER/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:111:9
                                                   wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
                                                   warningTimeout@/home/$USER/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:203:14
                                                   wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
Sep 10 14:00:24 $USER-buero gnome-shell[23404]: Usage of object.actor is deprecated for PrintersManager
                                                   get@resource:///org/gnome/shell/ui/environment.js:287:29
                                                   refresh/</</</<@/home/$USER/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:179:25
                                                   spawn_async@/home/$USER/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:36:5
                                                   refresh/</</<@/home/$USER/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:143:21
                                                   spawn_async@/home/$USER/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:36:5
                                                   refresh/</<@/home/$USER/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:133:17
                                                   spawn_async@/home/$USER/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:36:5
                                                   refresh/<@/home/$USER/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:113:13
                                                   spawn_async@/home/$USER/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:36:5
                                                   refresh@/home/$USER/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:111:9
                                                   wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
                                                   warningTimeout@/home/$USER/.local/share/gnome-shell/extensions/printers@linux-man.org/extension.js:203:14
                                                   wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27
`

**Comment by linux-man** [comment]
No good. The new file was not read. ALT-F2 r or logout-login?

**Comment by speedy-10** [comment]
ok, reboot, then it looks better:
`Sep 10 14:22:09 USER-buero systemd[1]: NetworkManager-dispatcher.service: Succeeded.
Sep 10 14:22:07 USER-buero gnome-shell[2254]: Window manager warning: Overwriting existing bindi>
Sep 10 14:22:07 USER-buero gnome-shell[2254]: Window manager warning: Overwriting existing bindi>
Sep 10 14:22:07 USER-buero gnome-shell[2254]: Window manager warning: Overwriting existing bindi>
Sep 10 14:22:07 USER-buero gnome-shell[2254]: Window manager warning: Overwriting existing bindi>
Sep 10 14:22:07 USER-buero gnome-shell[2254]: Window manager warning: Overwriting existing bindi>
Sep 10 14:22:07 USER-buero gnome-shell[2254]: Window manager warning: Overwriting existing bindi>
Sep 10 14:22:07 USER-buero gnome-shell[2254]: Window manager warning: Overwriting existing bindi>
Sep 10 14:22:07 USER-buero gnome-shell[2254]: Window manager warning: Overwriting existing bindi>
Sep 10 14:22:07 USER-buero gnome-shell[2254]: Window manager warning: Overwriting existing bindi>
Sep 10 14:22:07 USER-buero gnome-shell[2254]: Window manager warning: Overwriting existing bindi>
Sep 10 14:22:07 USER-buero systemd-resolved[536]: Using degraded feature set (UDP) for DNS serve>
Sep 10 14:22:07 USER-buero gnome-shell[2254]: st_widget_get_theme_node called on the widget [0x5>
Sep 10 14:22:07 USER-buero gnome-shell[2254]: st_widget_get_theme_node called on the widget [0x5>
Sep 10 14:22:07 USER-buero gnome-shell[2254]: st_widget_get_theme_node called on the widget [0x5>
Sep 10 14:22:07 USER-buero gnome-shell[2254]: st_widget_get_theme_node called on the widget [0x5>
Sep 10 14:22:07 USER-buero gnome-shell[2254]: st_widget_get_theme_node called on the widget [0x5>
Sep 10 14:22:07 USER-buero gnome-shell[2254]: Activities Configurator Enabled
Sep 10 14:22:05 USER-buero gnome-shell[2254]: [System monitor] applet enabling done
Sep 10 14:22:05 USER-buero gnome-shell[2254]: [System monitor] applet enabling
Sep 10 14:22:05 USER-buero dbus-daemon[1975]: [session uid=1000 pid=1975] Successfully activated>
Sep 10 14:22:05 USER-buero dbus-daemon[1975]: [session uid=1000 pid=1975] Activating service nam>
Sep 10 14:22:05 USER-buero NetworkManager[650]: <info>  [1599740525.7274] agent-manager: agent[e>
Sep 10 14:22:05 USER-buero gdm-password][4043]: gkr-pam: unlocked login keyring
`

**Comment by speedy-10** [comment]
Hi, i tried sometimes, only one login is needed, now everything is fine. Please consider this file for the next update. Thanks for your work for this extensions, I like it.
