### ISSUE TITLE
Add support for GNOME 40

### ISSUE THREAD

**Issue by Kerrung** [linux-man/gnome-shell-extension-printers#18]

**Comment by linux-man** [comment]
Is it time, already?
I'll take a look :wink:

**Comment by linux-man** [comment]
It's not all bad. The extension works without change except for the settings window, but I'm probably infringing a handful of guidelines and rules. Back to school.

**Comment by linux-man** [comment]
Done and uploaded to Gnome extensions. Let's test it.

**Comment by Kerrung** [comment]
> Done and uploaded to Gnome extensions. Let's test it.

Thank you so much!
