### ISSUE TITLE
lpstat output is read synchronously

### ISSUE THREAD

**Issue by juhaerk** [linux-man/gnome-shell-extension-printers#21]
This extension appears to read the output from "lpstat" (opened through spawn_async()) synchronously. In case cupsd and thus lpstat is slow to respond, this causes Gnome UI hangs.

This can be reproduced for example by replacing /usr/bin/lpstat with a shell script that only does "sleep 30". Gnome will then hang for 30 seconds each time the extension is reading printer information.

**Comment by linux-man** [comment]
@juhaerk Please check again. Big changes on latest version.

**Comment by linux-man** [comment]
Closed due to inactivity.
