### ISSUE TITLE
GNOME 41 compatibility

### ISSUE THREAD

**Issue by puyoxyz** [linux-man/gnome-shell-extension-printers#23]
title

**Comment by linux-man** [comment]
Have you installed the 40 version?

**Comment by puyoxyz** [comment]
yes, but it doesn't let you use it since it doesn't have gnome 41 in the compatible versions in the metadata

**Comment by linux-man** [comment]
I didn't install 41 yet. Todo.

**Comment by linux-man** [comment]
If you have it installed, could you edit ~/.local/share/gnome-shell/extensions/printers@linux.man.org/metadata.json and change version number at line 11 (40 to 41)? Just to see if the code is still compatible.

**Comment by puyoxyz** [comment]
> If you have it installed, could you edit ~/.local/share/gnome-shell/extensions/printers@linux.man.org/metadata.json and change version number at line 11 (40 to 41)? Just to see if the code is still compatible.


Seems to work fine.

**Comment by linux-man** [comment]
Let's try it.
