### ISSUE TITLE
Add support for GNOME 45

### ISSUE THREAD

**Issue by JoveYu** [linux-man/gnome-shell-extension-printers#26]

**Comment by linux-man** [comment]
Done.

**Comment by JoveYu** [comment]
GNOME Shell 45 moved to ESM (ECMAScript modules). That means you MUST use the standard import declaration instead of relying on the previous imports.* approach.

https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm

**Comment by linux-man** [comment]
It's working. Better menu management (it won't update when is open), Beautiful Adwaita prefs window.
