### ISSUE TITLE
Not working in gnome 46

### ISSUE THREAD

**Issue by foer** [linux-man/gnome-shell-extension-printers#27]
Adding version 46 to metadata is not enough sadly.

**Comment by linux-man** [comment]
That's odd, because "There were no relevant changes to extension.js in GNOME 46" so maybe there were changes on Gio or else. Looking for it.

**Comment by linux-man** [comment]
Update approved. Any feedback is appreciated.

**Comment by internauta2000** [comment]
On Manjaro w/ Gnome 46.2... The icon is showing in top bar, but when I click on it the menu does not appear with print jobs or shortcut to printer settings.

**Comment by linux-man** [comment]
Fixed.
