### ISSUE TITLE
Add support for GNOME 47

### ISSUE THREAD

**Issue by undefinedreality** [linux-man/gnome-shell-extension-printers#29]
Ubuntu 24.10 used gnome 47 by default.

**Comment by linux-man** [comment]
Done, but not tested!

**Comment by undefinedreality** [comment]
I have noticed the latest version (27) is works with gnome 47. Thanks for your impressively quick response.

**Comment by linux-man** [comment]
😊 It was just a version update. You should have seen the problem with upgrading to Gnome 46!!!
