### ISSUE TITLE
TypeError: out2.split(...)[1] is undefined

### ISSUE THREAD

**Issue by linux-man** [linux-man/gnome-shell-extension-printers#3]
What's wrong? -Installation failed.
What have you tried? -Installing the extension multiple times.
Automatically detected errors: TypeError: out2.split(...)[1] is undefined
Version information: Shell version: 3.24.2 Extension version: 2

**Comment by linux-man** [comment]
Can't replicate this bug on Ubuntu 16.04. Need more info.

**Comment by linux-man** [comment]
Version 3 uploaded.
Issue remains open until further notice (or lack of).

**Comment by jonnius** [comment]
Can't reproduce it anymore. So you may close this.

**Comment by linux-man** [comment]
Nevertheless, I uploaded a new version, available after reviewed.
