### ISSUE TITLE
GtkSwitch widget stretches to fill the available horizontal space

### ISSUE THREAD

**Issue by PJSingh5000** [linux-man/gnome-shell-extension-printers#9]
On the settings dialog, the GtkSwitch widget stretches to fill the available horizontal space.
A GtkSwitch should never stretch; it should always stay the same size.

This can be fixed in one of two ways:

1. Specify that the GtkSwitch does not expand horizontally, and right justify it in your container.

...or...

2. Add a widget (like a label without text) just in front of (to the left of) the GtkSwitch widget. Set this widget to expand to take up available horizontal space.

Here is what it looks like...

![screenshot from 2018-10-01 19-52-14](https://user-images.githubusercontent.com/19394936/46322650-25955c80-c5b8-11e8-85e1-b091f4850537.png)

Here is an example of what a GtkSwitch should look like:

![screenshot from 2018-10-01 20-19-42](https://user-images.githubusercontent.com/19394936/46322656-2b8b3d80-c5b8-11e8-94aa-58c2667b37b2.png)

**Comment by linux-man** [comment]
Extension uploaded - waiting for approval.

**Comment by PJSingh5000** [comment]
Perfect! Thank You!

![printers extension settings 2018-10-09](https://user-images.githubusercontent.com/19394936/46702900-f2278300-cbf2-11e8-9ed3-4362be943478.png)

![printers extension settings 2018-10-09-02](https://user-images.githubusercontent.com/19394936/46702973-36b31e80-cbf3-11e8-923a-e182fafe93ce.png)
